---
    
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy "cert" to html directory
  copy:
    src: templates/cert
    dest: /etc/ssl/

- name: Create "openpage.html"
  template:
    src: templates/openpage.html.j2
    dest: /var/www/html/openpage.html
    mode: 0644

- name: Change "nginx.conf" file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644
  vars:
    web: 'sbworld-web-1'
  when: ansible_facts.hostname == "web1"


- name: Change "nginx.conf" file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644
  vars:
    web: 'sbworld-web-2'
  when: ansible_facts.hostname == "web2"

- name: Copy "opensb.png" to html directory
  copy:
    src: templates/opensb.png
    dest: /var/www/html/opensb.png
    

- name: Enable default Nginx website
  file:
    src: /etc/nginx/sites-available/default
    path: /etc/nginx/sites-enabled/default
    state: link

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
