- name: stop Slave
  mysql_replication:
    mode: stopreplica
- name: configure mysql Slave
  mysql_replication:
    master_host: "{{ master }}" # master db server ip
    master_user: admin # M - S 연결 관리자 계정
    master_password: 'Passw0rd'
    master_log_file: mysql-bin.000002 # Master 정보 넣어준다
    master_log_pos: 157
    mode: changeprimary

- name: start Slave
  mysql_replication:
    mode: resetreplica

- name: Restart mysql
  service:
    name: mysql
    state: restarted
