
- name: update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Copy "cert" for ssl
  copy:
    src: templates/cert
    dest: /etc/ssl/

- name: Create a Tomcat User
  user:
    name: tomcat

- name: Create a Tomcat Group
  group:
    name: tomcat

- name: Install JAVA on ubuntu
  apt:
    name: default-jdk
    state: present

- name: Create a Tomcat Directory
  file:
    path: /usr/share/tomcat
    owner: tomcat
    group: tomcat
    mode: 0755
    state: directory

- name: download tomcat10
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.7/bin/apache-tomcat-10.0.7.tar.gz
    dest: /tmp/apache-tomcat-10.0.7.tar.gz

- name: Extract tomcat archive
  unarchive:
    src: /tmp/apache-tomcat-10.0.7.tar.gz
    dest: /usr/share/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /usr/share/tomcat/bin

- name: Copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"


- name: Copy tomcat web file
  template:
    src: templates/web.xml.j2
    dest: /usr/share/tomcat/conf/web.xml
  when: ansible_service_mgr == "systemd"

- name: Copy tomcat sb.jsp file
  template:
    src: templates/sbworld.j2
    dest: /usr/share/tomcat/webapps/ROOT/sbworld.jsp
    owner: tomcat
    group: tomcat
  when: ansible_service_mgr == "systemd"

- name: Copy tomcat jar1
  copy:
    src: templates/mysql-connector-j-8.4.0.jar
    dest: /usr/share/tomcat/lib
    owner: tomcat
    group: tomcat
  when: ansible_service_mgr == "systemd"

- name: Copy tomcat jar2
  copy:
    src: templates/mysql-connector-java-8.4.0.jar
    dest: /usr/share/tomcat/lib
    owner: tomcat
    group: tomcat
  when: ansible_service_mgr == "systemd"

- name: Set UI access credentials
  template:
    src: tomcat-users.xml.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml

- name: Insert Connector block after <Service name="Catalina">
  blockinfile:
    path: /usr/share/tomcat/conf/server.xml
    marker: <!-- {mark} -->
    insertafter: '<Service name="Catalina">'
    block: |
      <Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true">
        <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />
        <SSLHostConfig>
          <Certificate certificateKeystoreFile="/usr/share/tomcat/conf/sbcert.jks" certificateKeystorePassword="ddimtech21!" type="RSA" />
        </SSLHostConfig>
      </Connector>

- name: Copy "sbcert.jks" to was server.xml
  copy:
    src: templates/sbcert.jks
    dest: /usr/share/tomcat/conf/
    owner: tomcat
    group: tomcat
- name: Daemon reload.
  command: systemctl daemon-reload

- name: Starting Apache Tomcat service.
  service: name=tomcat state=started
